// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: downstream_tokens.sql

package storage

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDownstreamToken = `-- name: CreateDownstreamToken :one
INSERT INTO downstream_tokens (
    policy_id,
    token_hash,
    name,
    expires_at
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, policy_id, token_hash, name, expires_at, last_used_at, revoked, created_at, updated_at
`

type CreateDownstreamTokenParams struct {
	PolicyID  pgtype.UUID        `json:"policy_id"`
	TokenHash string             `json:"token_hash"`
	Name      string             `json:"name"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateDownstreamToken(ctx context.Context, arg CreateDownstreamTokenParams) (DownstreamToken, error) {
	row := q.db.QueryRow(ctx, createDownstreamToken,
		arg.PolicyID,
		arg.TokenHash,
		arg.Name,
		arg.ExpiresAt,
	)
	var i DownstreamToken
	err := row.Scan(
		&i.ID,
		&i.PolicyID,
		&i.TokenHash,
		&i.Name,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.Revoked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDownstreamToken = `-- name: DeleteDownstreamToken :exec
DELETE FROM downstream_tokens
WHERE id = $1
`

func (q *Queries) DeleteDownstreamToken(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDownstreamToken, id)
	return err
}

const getDownstreamTokenByHash = `-- name: GetDownstreamTokenByHash :one
SELECT
    dt.id, dt.policy_id, dt.token_hash, dt.name, dt.expires_at, dt.last_used_at, dt.revoked, dt.created_at, dt.updated_at,
    p.id, p.user_id, p.version, p.base_url, p.default_action, p.rules, p.is_active, p.created_at, p.updated_at, p.upstream_credential_id,
    uc.id, uc.user_id, uc.name, uc.token, uc.api_endpoint, uc.token_type, uc.expires_at, uc.created_at, uc.updated_at
FROM downstream_tokens dt
JOIN policies p ON p.id = dt.policy_id
JOIN upstream_credentials uc ON uc.id = p.upstream_credential_id
WHERE dt.token_hash = $1
  AND dt.revoked = FALSE
  AND (dt.expires_at IS NULL OR dt.expires_at > NOW())
  AND p.is_active = TRUE
  AND (uc.expires_at IS NULL OR uc.expires_at > NOW())
`

type GetDownstreamTokenByHashRow struct {
	ID                 pgtype.UUID        `json:"id"`
	PolicyID           pgtype.UUID        `json:"policy_id"`
	TokenHash          string             `json:"token_hash"`
	Name               string             `json:"name"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt         pgtype.Timestamptz `json:"last_used_at"`
	Revoked            bool               `json:"revoked"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	Policy             Policy             `json:"policy"`
	UpstreamCredential UpstreamCredential `json:"upstream_credential"`
}

func (q *Queries) GetDownstreamTokenByHash(ctx context.Context, tokenHash string) (GetDownstreamTokenByHashRow, error) {
	row := q.db.QueryRow(ctx, getDownstreamTokenByHash, tokenHash)
	var i GetDownstreamTokenByHashRow
	err := row.Scan(
		&i.ID,
		&i.PolicyID,
		&i.TokenHash,
		&i.Name,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.Revoked,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Policy.ID,
		&i.Policy.UserID,
		&i.Policy.Version,
		&i.Policy.BaseUrl,
		&i.Policy.DefaultAction,
		&i.Policy.Rules,
		&i.Policy.IsActive,
		&i.Policy.CreatedAt,
		&i.Policy.UpdatedAt,
		&i.Policy.UpstreamCredentialID,
		&i.UpstreamCredential.ID,
		&i.UpstreamCredential.UserID,
		&i.UpstreamCredential.Name,
		&i.UpstreamCredential.Token,
		&i.UpstreamCredential.ApiEndpoint,
		&i.UpstreamCredential.TokenType,
		&i.UpstreamCredential.ExpiresAt,
		&i.UpstreamCredential.CreatedAt,
		&i.UpstreamCredential.UpdatedAt,
	)
	return i, err
}

const listDownstreamTokensByPolicyID = `-- name: ListDownstreamTokensByPolicyID :many
SELECT id, policy_id, token_hash, name, expires_at, last_used_at, revoked, created_at, updated_at FROM downstream_tokens
WHERE policy_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListDownstreamTokensByPolicyID(ctx context.Context, policyID pgtype.UUID) ([]DownstreamToken, error) {
	rows, err := q.db.Query(ctx, listDownstreamTokensByPolicyID, policyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DownstreamToken
	for rows.Next() {
		var i DownstreamToken
		if err := rows.Scan(
			&i.ID,
			&i.PolicyID,
			&i.TokenHash,
			&i.Name,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.Revoked,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeDownstreamToken = `-- name: RevokeDownstreamToken :exec
UPDATE downstream_tokens
SET
    revoked = TRUE,
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) RevokeDownstreamToken(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeDownstreamToken, id)
	return err
}

const updateDownstreamTokenLastUsed = `-- name: UpdateDownstreamTokenLastUsed :exec
UPDATE downstream_tokens
SET last_used_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateDownstreamTokenLastUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateDownstreamTokenLastUsed, id)
	return err
}
