// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: policies.sql

package storage

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activatePolicy = `-- name: ActivatePolicy :exec
UPDATE policies SET is_active = TRUE WHERE id = $1
`

func (q *Queries) ActivatePolicy(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, activatePolicy, id)
	return err
}

const createPolicy = `-- name: CreatePolicy :one
INSERT INTO policies (user_id, token, version, base_url, default_action, rules, is_active)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, token, version, base_url, default_action, rules, is_active, created_at, updated_at
`

type CreatePolicyParams struct {
	UserID        pgtype.UUID `json:"user_id"`
	Token         string      `json:"token"`
	Version       string      `json:"version"`
	BaseUrl       string      `json:"base_url"`
	DefaultAction string      `json:"default_action"`
	Rules         []byte      `json:"rules"`
	IsActive      bool        `json:"is_active"`
}

func (q *Queries) CreatePolicy(ctx context.Context, arg CreatePolicyParams) (Policy, error) {
	row := q.db.QueryRow(ctx, createPolicy,
		arg.UserID,
		arg.Token,
		arg.Version,
		arg.BaseUrl,
		arg.DefaultAction,
		arg.Rules,
		arg.IsActive,
	)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.Version,
		&i.BaseUrl,
		&i.DefaultAction,
		&i.Rules,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateUserPolicies = `-- name: DeactivateUserPolicies :exec
UPDATE policies SET is_active = FALSE WHERE user_id = $1
`

func (q *Queries) DeactivateUserPolicies(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deactivateUserPolicies, userID)
	return err
}

const getActivePolicyForUser = `-- name: GetActivePolicyForUser :one
SELECT id, user_id, token, version, base_url, default_action, rules, is_active, created_at, updated_at FROM policies
WHERE user_id = $1 AND is_active = TRUE
LIMIT 1
`

func (q *Queries) GetActivePolicyForUser(ctx context.Context, userID pgtype.UUID) (Policy, error) {
	row := q.db.QueryRow(ctx, getActivePolicyForUser, userID)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.Version,
		&i.BaseUrl,
		&i.DefaultAction,
		&i.Rules,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPolicyVersions = `-- name: ListPolicyVersions :many
SELECT id, user_id, token, version, base_url, default_action, rules, is_active, created_at, updated_at FROM policies
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListPolicyVersions(ctx context.Context, userID pgtype.UUID) ([]Policy, error) {
	rows, err := q.db.Query(ctx, listPolicyVersions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Policy
	for rows.Next() {
		var i Policy
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Token,
			&i.Version,
			&i.BaseUrl,
			&i.DefaultAction,
			&i.Rules,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
