// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: policy_rules.sql

package storage

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPolicyRule = `-- name: CreatePolicyRule :one
INSERT INTO policy_rules (policy_id, route, method, action, response_filter, priority)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, policy_id, route, method, action, response_filter, priority
`

type CreatePolicyRuleParams struct {
	PolicyID       pgtype.UUID `json:"policy_id"`
	Route          string      `json:"route"`
	Method         string      `json:"method"`
	Action         string      `json:"action"`
	ResponseFilter []byte      `json:"response_filter"`
	Priority       int32       `json:"priority"`
}

func (q *Queries) CreatePolicyRule(ctx context.Context, arg CreatePolicyRuleParams) (PolicyRule, error) {
	row := q.db.QueryRow(ctx, createPolicyRule,
		arg.PolicyID,
		arg.Route,
		arg.Method,
		arg.Action,
		arg.ResponseFilter,
		arg.Priority,
	)
	var i PolicyRule
	err := row.Scan(
		&i.ID,
		&i.PolicyID,
		&i.Route,
		&i.Method,
		&i.Action,
		&i.ResponseFilter,
		&i.Priority,
	)
	return i, err
}

const getRulesForPolicy = `-- name: GetRulesForPolicy :many
SELECT id, policy_id, route, method, action, response_filter, priority FROM policy_rules
WHERE policy_id = $1
ORDER BY priority DESC, id
`

func (q *Queries) GetRulesForPolicy(ctx context.Context, policyID pgtype.UUID) ([]PolicyRule, error) {
	rows, err := q.db.Query(ctx, getRulesForPolicy, policyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PolicyRule
	for rows.Next() {
		var i PolicyRule
		if err := rows.Scan(
			&i.ID,
			&i.PolicyID,
			&i.Route,
			&i.Method,
			&i.Action,
			&i.ResponseFilter,
			&i.Priority,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
