// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package storage

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ActivatePolicy(ctx context.Context, id pgtype.UUID) error
	CreatePolicy(ctx context.Context, arg CreatePolicyParams) (Policy, error)
	CreateUser(ctx context.Context, email string) (User, error)
	DeactivateUserPolicies(ctx context.Context, userID pgtype.UUID) error
	GetActivePolicyByToken(ctx context.Context, token string) (Policy, error)
	GetActivePolicyForUser(ctx context.Context, userID pgtype.UUID) (Policy, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	ListPolicyVersions(ctx context.Context, userID pgtype.UUID) ([]Policy, error)
}

var _ Querier = (*Queries)(nil)
