// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package storage

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ActivatePolicy(ctx context.Context, id pgtype.UUID) error
	CreatePolicy(ctx context.Context, arg CreatePolicyParams) (Policy, error)
	CreatePolicyRule(ctx context.Context, arg CreatePolicyRuleParams) (PolicyRule, error)
	CreateRateLimit(ctx context.Context, arg CreateRateLimitParams) (RateLimit, error)
	CreateToken(ctx context.Context, arg CreateTokenParams) (Token, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeactivateUserPolicies(ctx context.Context, userID pgtype.UUID) error
	GetActivePolicyForUser(ctx context.Context, userID pgtype.UUID) (Policy, error)
	GetRateLimitForToken(ctx context.Context, arg GetRateLimitForTokenParams) (RateLimit, error)
	GetRulesForPolicy(ctx context.Context, policyID pgtype.UUID) ([]PolicyRule, error)
	GetTokenByJTI(ctx context.Context, jti string) (Token, error)
	GetTokenUsage(ctx context.Context, arg GetTokenUsageParams) (TokenUsage, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	IncrementTokenUsage(ctx context.Context, arg IncrementTokenUsageParams) (TokenUsage, error)
	ListActiveTokensForUser(ctx context.Context, userID pgtype.UUID) ([]Token, error)
	ListPolicyVersions(ctx context.Context, userID pgtype.UUID) ([]Policy, error)
	RevokeToken(ctx context.Context, jti string) error
	UpdateTokenLastUsed(ctx context.Context, jti string) error
}

var _ Querier = (*Queries)(nil)
