// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: rate_limits.sql

package storage

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRateLimit = `-- name: CreateRateLimit :one
INSERT INTO rate_limits (token_id, endpoint, limit_type, requests_limit, window_seconds)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, token_id, endpoint, limit_type, requests_limit, window_seconds
`

type CreateRateLimitParams struct {
	TokenID       pgtype.UUID `json:"token_id"`
	Endpoint      string      `json:"endpoint"`
	LimitType     string      `json:"limit_type"`
	RequestsLimit int32       `json:"requests_limit"`
	WindowSeconds int32       `json:"window_seconds"`
}

func (q *Queries) CreateRateLimit(ctx context.Context, arg CreateRateLimitParams) (RateLimit, error) {
	row := q.db.QueryRow(ctx, createRateLimit,
		arg.TokenID,
		arg.Endpoint,
		arg.LimitType,
		arg.RequestsLimit,
		arg.WindowSeconds,
	)
	var i RateLimit
	err := row.Scan(
		&i.ID,
		&i.TokenID,
		&i.Endpoint,
		&i.LimitType,
		&i.RequestsLimit,
		&i.WindowSeconds,
	)
	return i, err
}

const getRateLimitForToken = `-- name: GetRateLimitForToken :one
SELECT id, token_id, endpoint, limit_type, requests_limit, window_seconds FROM rate_limits
WHERE token_id = $1 AND endpoint = $2 AND limit_type = $3
LIMIT 1
`

type GetRateLimitForTokenParams struct {
	TokenID   pgtype.UUID `json:"token_id"`
	Endpoint  string      `json:"endpoint"`
	LimitType string      `json:"limit_type"`
}

func (q *Queries) GetRateLimitForToken(ctx context.Context, arg GetRateLimitForTokenParams) (RateLimit, error) {
	row := q.db.QueryRow(ctx, getRateLimitForToken, arg.TokenID, arg.Endpoint, arg.LimitType)
	var i RateLimit
	err := row.Scan(
		&i.ID,
		&i.TokenID,
		&i.Endpoint,
		&i.LimitType,
		&i.RequestsLimit,
		&i.WindowSeconds,
	)
	return i, err
}

const getTokenUsage = `-- name: GetTokenUsage :one
SELECT id, token_id, endpoint, window_start, request_count, last_request_at FROM token_usage
WHERE token_id = $1 AND endpoint = $2 AND window_start = $3
LIMIT 1
`

type GetTokenUsageParams struct {
	TokenID     pgtype.UUID        `json:"token_id"`
	Endpoint    string             `json:"endpoint"`
	WindowStart pgtype.Timestamptz `json:"window_start"`
}

func (q *Queries) GetTokenUsage(ctx context.Context, arg GetTokenUsageParams) (TokenUsage, error) {
	row := q.db.QueryRow(ctx, getTokenUsage, arg.TokenID, arg.Endpoint, arg.WindowStart)
	var i TokenUsage
	err := row.Scan(
		&i.ID,
		&i.TokenID,
		&i.Endpoint,
		&i.WindowStart,
		&i.RequestCount,
		&i.LastRequestAt,
	)
	return i, err
}

const incrementTokenUsage = `-- name: IncrementTokenUsage :one
INSERT INTO token_usage (token_id, endpoint, window_start, request_count, last_request_at)
VALUES ($1, $2, $3, 1, NOW())
ON CONFLICT (token_id, endpoint, window_start)
DO UPDATE SET
    request_count = token_usage.request_count + 1,
    last_request_at = NOW()
RETURNING id, token_id, endpoint, window_start, request_count, last_request_at
`

type IncrementTokenUsageParams struct {
	TokenID     pgtype.UUID        `json:"token_id"`
	Endpoint    string             `json:"endpoint"`
	WindowStart pgtype.Timestamptz `json:"window_start"`
}

func (q *Queries) IncrementTokenUsage(ctx context.Context, arg IncrementTokenUsageParams) (TokenUsage, error) {
	row := q.db.QueryRow(ctx, incrementTokenUsage, arg.TokenID, arg.Endpoint, arg.WindowStart)
	var i TokenUsage
	err := row.Scan(
		&i.ID,
		&i.TokenID,
		&i.Endpoint,
		&i.WindowStart,
		&i.RequestCount,
		&i.LastRequestAt,
	)
	return i, err
}
