// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: tokens.sql

package storage

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createToken = `-- name: CreateToken :one
INSERT INTO tokens (user_id, jti, token_hash, scopes, issued_at, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, jti, token_hash, scopes, issued_at, expires_at, revoked_at, last_used_at
`

type CreateTokenParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	Jti       string             `json:"jti"`
	TokenHash string             `json:"token_hash"`
	Scopes    []string           `json:"scopes"`
	IssuedAt  pgtype.Timestamptz `json:"issued_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) (Token, error) {
	row := q.db.QueryRow(ctx, createToken,
		arg.UserID,
		arg.Jti,
		arg.TokenHash,
		arg.Scopes,
		arg.IssuedAt,
		arg.ExpiresAt,
	)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Jti,
		&i.TokenHash,
		&i.Scopes,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getTokenByJTI = `-- name: GetTokenByJTI :one
SELECT id, user_id, jti, token_hash, scopes, issued_at, expires_at, revoked_at, last_used_at FROM tokens WHERE jti = $1 LIMIT 1
`

func (q *Queries) GetTokenByJTI(ctx context.Context, jti string) (Token, error) {
	row := q.db.QueryRow(ctx, getTokenByJTI, jti)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Jti,
		&i.TokenHash,
		&i.Scopes,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const listActiveTokensForUser = `-- name: ListActiveTokensForUser :many
SELECT id, user_id, jti, token_hash, scopes, issued_at, expires_at, revoked_at, last_used_at FROM tokens
WHERE user_id = $1
  AND revoked_at IS NULL
  AND expires_at > NOW()
ORDER BY issued_at DESC
`

func (q *Queries) ListActiveTokensForUser(ctx context.Context, userID pgtype.UUID) ([]Token, error) {
	rows, err := q.db.Query(ctx, listActiveTokensForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Token
	for rows.Next() {
		var i Token
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Jti,
			&i.TokenHash,
			&i.Scopes,
			&i.IssuedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeToken = `-- name: RevokeToken :exec
UPDATE tokens SET revoked_at = NOW() WHERE jti = $1
`

func (q *Queries) RevokeToken(ctx context.Context, jti string) error {
	_, err := q.db.Exec(ctx, revokeToken, jti)
	return err
}

const updateTokenLastUsed = `-- name: UpdateTokenLastUsed :exec
UPDATE tokens SET last_used_at = NOW() WHERE jti = $1
`

func (q *Queries) UpdateTokenLastUsed(ctx context.Context, jti string) error {
	_, err := q.db.Exec(ctx, updateTokenLastUsed, jti)
	return err
}
