// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: upstream_credentials.sql

package storage

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUpstreamCredential = `-- name: CreateUpstreamCredential :one
INSERT INTO upstream_credentials (
    user_id,
    name,
    token,
    api_endpoint,
    token_type,
    expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, user_id, name, token, api_endpoint, token_type, expires_at, created_at, updated_at
`

type CreateUpstreamCredentialParams struct {
	UserID      pgtype.UUID        `json:"user_id"`
	Name        string             `json:"name"`
	Token       string             `json:"token"`
	ApiEndpoint *string            `json:"api_endpoint"`
	TokenType   *string            `json:"token_type"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateUpstreamCredential(ctx context.Context, arg CreateUpstreamCredentialParams) (UpstreamCredential, error) {
	row := q.db.QueryRow(ctx, createUpstreamCredential,
		arg.UserID,
		arg.Name,
		arg.Token,
		arg.ApiEndpoint,
		arg.TokenType,
		arg.ExpiresAt,
	)
	var i UpstreamCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Token,
		&i.ApiEndpoint,
		&i.TokenType,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUpstreamCredential = `-- name: DeleteUpstreamCredential :exec
DELETE FROM upstream_credentials
WHERE id = $1
`

func (q *Queries) DeleteUpstreamCredential(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUpstreamCredential, id)
	return err
}

const getUpstreamCredentialByID = `-- name: GetUpstreamCredentialByID :one
SELECT id, user_id, name, token, api_endpoint, token_type, expires_at, created_at, updated_at FROM upstream_credentials
WHERE id = $1
`

func (q *Queries) GetUpstreamCredentialByID(ctx context.Context, id pgtype.UUID) (UpstreamCredential, error) {
	row := q.db.QueryRow(ctx, getUpstreamCredentialByID, id)
	var i UpstreamCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Token,
		&i.ApiEndpoint,
		&i.TokenType,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveUpstreamCredentials = `-- name: ListActiveUpstreamCredentials :many
SELECT id, user_id, name, token, api_endpoint, token_type, expires_at, created_at, updated_at FROM upstream_credentials
WHERE user_id = $1
  AND (expires_at IS NULL OR expires_at > NOW())
ORDER BY created_at DESC
`

func (q *Queries) ListActiveUpstreamCredentials(ctx context.Context, userID pgtype.UUID) ([]UpstreamCredential, error) {
	rows, err := q.db.Query(ctx, listActiveUpstreamCredentials, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UpstreamCredential
	for rows.Next() {
		var i UpstreamCredential
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Token,
			&i.ApiEndpoint,
			&i.TokenType,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpstreamCredentialsByUserID = `-- name: ListUpstreamCredentialsByUserID :many
SELECT id, user_id, name, token, api_endpoint, token_type, expires_at, created_at, updated_at FROM upstream_credentials
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListUpstreamCredentialsByUserID(ctx context.Context, userID pgtype.UUID) ([]UpstreamCredential, error) {
	rows, err := q.db.Query(ctx, listUpstreamCredentialsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UpstreamCredential
	for rows.Next() {
		var i UpstreamCredential
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Token,
			&i.ApiEndpoint,
			&i.TokenType,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUpstreamCredential = `-- name: UpdateUpstreamCredential :one
UPDATE upstream_credentials
SET
    name = COALESCE($2, name),
    token = COALESCE($3, token),
    api_endpoint = COALESCE($4, api_endpoint),
    token_type = COALESCE($5, token_type),
    expires_at = COALESCE($6, expires_at),
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, name, token, api_endpoint, token_type, expires_at, created_at, updated_at
`

type UpdateUpstreamCredentialParams struct {
	ID          pgtype.UUID        `json:"id"`
	Name        *string            `json:"name"`
	Token       *string            `json:"token"`
	ApiEndpoint *string            `json:"api_endpoint"`
	TokenType   *string            `json:"token_type"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) UpdateUpstreamCredential(ctx context.Context, arg UpdateUpstreamCredentialParams) (UpstreamCredential, error) {
	row := q.db.QueryRow(ctx, updateUpstreamCredential,
		arg.ID,
		arg.Name,
		arg.Token,
		arg.ApiEndpoint,
		arg.TokenType,
		arg.ExpiresAt,
	)
	var i UpstreamCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Token,
		&i.ApiEndpoint,
		&i.TokenType,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
